### ISSUE TITLE
Cursor positions to next line after insertion

### ISSUE THREAD

**Issue by gerbz** [Gru80/obsidian-timestamper#2]
Just the plugin I was looking for!  When I hit my hotkey, it inserts the template perfectly, but my cursor is now on the next line down.  Any way to prevent this?

**Comment by Gru80** [comment]
Actually the line break is inserted automatically at the moment - however I understand that this is not necessarily a wanted behaviour in all use cases.
I'll consider that in the next version and introduce a parameter in the plugin-settings to specify whether a line break should be inserted or not

**Comment by Gru80** [comment]
Option not included in V1.2.0
