### ISSUE TITLE
[Feature Request] Be able to configure after newline

### ISSUE THREAD

**Issue by WeisseTeetasse** [Gru80/obsidian-timestamper#3]
Hey There,

what I am trying to accomplish with Timestamper is something that looks like this:

[Picture](https://ibb.co/QcSwL7r)

There is already an option to add a newline, which is nice, could it maybe be possible to configure what's in the new line as well?
A Tab and a * in my case.

**Comment by Gru80** [comment]
Hi :-)

actually with the current set of options it is only possible to choose between inserting a line-break or not (I also tried to keep that as simple as possible).

For enhanced customization, I would highly recommend you to have a closer look at Obsidian Templates: https://help.obsidian.md/Plugins/Templates
It is a native Obsidian Plugin which allows you to create template-notes that can be inserted in any other note by command - and you can also use the same time/date-stamp syntax. 
I think that should perfectly match your requirements.

best regards,
Martin

**Comment by WeisseTeetasse** [comment]
Servus und Danke :)
